require "active_support/core_ext/integer/time"
require 'pathname'
require 'fileutils'

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Write Rails logs to project root logs/ (not server/logs)
  root_logs = if ENV['SAVANT_LOG_PATH'] && !ENV['SAVANT_LOG_PATH'].empty?
                Pathname.new(ENV['SAVANT_LOG_PATH']).expand_path
              else
                Rails.root.join('..', 'logs').expand_path
              end
  FileUtils.mkdir_p(root_logs)
  config.paths["log"] = root_logs.join("rails-development.log")

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Exclude large directories from file watcher to prevent EMFILE errors
  config.watch_manifest_manifests = false
  config.file_watcher = ActiveSupport::FileUpdateChecker
  # Directories to exclude from file watching
  config.watchable_dirs.delete(Rails.root.join('public'))
  config.watchable_dirs.delete(Rails.root.join('tmp'))
  config.watchable_dirs.delete(Rails.root.join('.git'))
  # Remove locales dir from watch to avoid scanning the directory each request
  begin
    config.watchable_dirs.delete(Rails.root.join('config', 'locales'))
  rescue StandardError
  end
  # Tighten watch set to just app/ and lib/ Ruby sources
  begin
    config.watchable_dirs = {
      Rails.root.join('app') => [:rb],
      Rails.root.join('lib') => [:rb]
    }
  rescue StandardError
  end
  # Limit I18n load path to a single locale file to minimize directory handles
  begin
    I18n.load_path = [Rails.root.join('config', 'locales', 'en.yml').to_s]
  rescue StandardError
  end


  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Ensure concurrent requests in dev (needed for SSE streams not to block).
  config.allow_concurrency = true

  # Serve files in /public (for static UI under /ui)
  config.public_file_server.enabled = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.cache_store = :memory_store
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
